image: gitlab/dind

stages:
  - test

before_script:
  - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  - apt-get update
  - apt-get install -y docker
  - apt-get install -y software-properties-common
  - add-apt-repository -y ppa:webupd8team/java
  - apt-get update
  - apt-get install -y oracle-java8-installer

test:
  script:
    - docker build -t postgres-acme db
    - docker --name acme-invoice-test run -p 5433:5432 -e POSTGRES_PASSWORD=vandebron -d postgres-acme
    - ./gradlew test
    - docker stop acme-invoice-test