sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t postgres-acme db
  - docker run --name acme-invoice-test -p 5433:5432 -e POSTGRES_PASSWORD=password -d postgres-acme

after_script:
  - docker stop acme-invoice-test

script:
  - ./gradlew unitTests
  - ./gradlew integrationTests
  - ./gradlew endToEndTests