version: '2'
services:
  db:
    container_name: postgres
    build: ./db/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

  deploy:
    container_name: tomcat
    build: .
    ports:
      - "9000:9000"
    links:
      - db:postgres